import Head from 'next/head'
import Image from 'next/image'
import Currencies from '../components/currencies'
import Header from '../components/header'
import { MainWrapper } from '../components/mainWrapper'
import Poisk from '../components/poisk'


import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pumpkin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className='min-h-screen bg-bg-light'>
        <Header />
        
        <Poisk />

        <body className=''>

        </body>
      </main> */}
      <div className='min-h-screen bg-bg-light font-lato'>
        <div className='bg-bg-dark w-full lg:px-16'>
          <MainWrapper>


            <Header />

          </MainWrapper>
        </div>
        <div className='bg-bg-dark w-full'>
          <MainWrapper>
            <Currencies />

          </MainWrapper>
        </div>
        <div className=' w-full'>
          <MainWrapper>


            <Poisk />

          </MainWrapper>
        </div>
      </div>

      {/* <footer className={styles.footer}>

      </footer> */}
    </div>
  )
}
